export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const UPDATE_USER_INFO = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAIL = 'UPDATE_USER_ADDRESS_FAIL';

export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const UPDATE_USER_EMAIL_SUCCESS = 'UPDATE_USER_EMAIL_SUCCESS';
export const UPDATE_USER_EMAIL_FAIL = 'UPDATE_USER_EMAIL_FAIL';

export const UPDATE_USER_SOCIAL = 'UPDATE_USER_SOCIAL';
export const UPDATE_USER_SOCIAL_SUCCESS = 'UPDATE_USER_SOCIAL_SUCCESS';
export const UPDATE_USER_SOCIAL_FAIL = 'UPDATE_USER_SOCIAL_FAIL';

export const UPDATE_USER_MESSANGERS = 'UPDATE_USER_MESSANGERS';
export const UPDATE_USER_MESSANGERS_SUCCESS = 'UPDATE_USER_MESSANGERS_SUCCESS';
export const UPDATE_USER_MESSANGERS_FAIL = 'UPDATE_USER_MESSANGERS_FAIL';

export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';
export const UPDATE_USER_PHOTO_SUCCESS = 'UPDATE_USER_PHOTO_SUCCESS';
export const UPDATE_USER_PHOTO_FAIL = 'UPDATE_USER_PHOTO_FAIL';

export const UPDATE_USER_LANGUAGES = 'UPDATE_USER_LANGUAGES';
export const UPDATE_USER_LANGUAGES_SUCCESS = 'UPDATE_USER_LANGUAGES_SUCCESS';
export const UPDATE_USER_LANGUAGES_FAIL = 'UPDATE_USER_LANGUAGES_FAIL';

export const UPDATE_USER_EXPERIENCE = 'UPDATE_USER_EXPERIENCE';
export const UPDATE_USER_EXPERIENCE_SUCCESS = 'UPDATE_USER_EXPERIENCE_SUCCESS';
export const UPDATE_USER_EXPERIENCE_FAIL = 'UPDATE_USER_EXPERIENCE_FAIL';

export const UPDATE_USER_GRADUATION = 'UPDATE_USER_GRADUATION';
export const UPDATE_USER_GRADUATION_SUCCESS = 'UPDATE_USER_GRADUATION_SUCCESS';
export const UPDATE_USER_GRADUATION_FAIL = 'UPDATE_USER_GRADUATION_FAIL';

export const UPDATE_USER_COURSES = 'UPDATE_USER_COURSES';
export const UPDATE_USER_COURSES_SUCCESS = 'UPDATE_USER_COURSES_SUCCESS';
export const UPDATE_USER_COURSES_FAIL = 'UPDATE_USER_COURSES_FAIL';

export const UPDATE_USER_CERTIFICATES = 'UPDATE_USER_CERTIFICATES';
export const UPDATE_USER_CERTIFICATES_SUCCESS = 'UPDATE_USER_CERTIFICATES_SUCCESS';
export const UPDATE_USER_CERTIFICATES_FAIL = 'UPDATE_USER_CERTIFICATES_FAIL';

export const CONFIRM_USER_PHONE = 'CONFIRM_USER_PHONE';
export const CONFIRM_USER_PHONE_SUCCESS = 'CONFIRM_USER_PHONE_SUCCESS';
export const CONFIRM_USER_PHONE_FAIL = 'CONFIRM_USER_PHONE_FAIL';

export const CONFIRM_USER_PIN_CODE = 'CONFIRM_USER_PIN_CODE';
export const CONFIRM_USER_PIN_CODE_SUCCESS = 'CONFIRM_USER_PIN_CODE_SUCCESS';
export const CONFIRM_USER_PIN_CODE_FAIL = 'CONFIRM_USER_PIN_CODE_FAIL';

export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS';
export const FETCH_LANGUAGES_FAIL = 'FETCH_LANGUAGES_FAIL';

export const FETCH_LANGUAGE_SKILLS = 'FETCH_LANGUAGE_SKILLS';
export const FETCH_LANGUAGE_SKILLS_SUCCESS = 'FETCH_LANGUAGE_SKILLS_SUCCESS';
export const FETCH_LANGUAGE_SKILLS_FAIL = 'FETCH_LANGUAGE_SKILLS_FAIL';

export const FETCH_POSITIONS = 'FETCH_POSITIONS';
export const FETCH_POSITIONS_SUCCESS = 'FETCH_POSITIONS_SUCCESS';
export const FETCH_POSITIONS_FAIL = 'FETCH_POSITIONS_FAIL';

export const FETCH_LEVEL_INSTITUTIONS = 'FETCH_LEVEL_INSTITUTIONS';
export const FETCH_LEVEL_INSTITUTIONS_SUCCESS = 'FETCH_LEVEL_INSTITUTIONS_SUCCESS';
export const FETCH_LEVEL_INSTITUTIONS_FAIL = 'FETCH_LEVEL_INSTITUTIONS_FAIL';

export const FETCH_INSTITUTIONS = 'FETCH_INSTITUTIONS';
export const FETCH_INSTITUTIONS_SUCCESS = 'FETCH_INSTITUTIONS_SUCCESS';
export const FETCH_INSTITUTIONS_FAIL = 'FETCH_INSTITUTIONS_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTRATION_USER = 'REGISTRATION_USER';
export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS';
export const REGISTRATION_USER_FAIL = 'REGISTRATION_USER_FAIL';

export const PASSWORD_RESET_USER = 'PASSWORD_RESET_USER';
export const PASSWORD_RESET_USER_SUCCESS = 'PASSWORD_RESET_USER_SUCCESS';
export const PASSWORD_RESET_USER_FAIL = 'PASSWORD_RESET_USER_FAIL';

export const NEW_PASSWORD_SAVE_USER = 'NEW_PASSWORD_SAVE_USER';
export const NEW_PASSWORD_SAVE_USER_SUCCESS = 'NEW_PASSWORD_SAVE_USER_SUCCESS';
export const NEW_PASSWORD_SAVE_USER_FAIL = 'NEW_PASSWORD_SAVE_USER_FAIL';

export const FETCH_EDUCATION_LEVELS = 'FETCH_EDUCATION_LEVELS';
export const FETCH_EDUCATION_LEVELS_SUCCESS = 'FETCH_EDUCATION_LEVELS_SUCCESS';
export const FETCH_EDUCATION_LEVELS_FAIL = 'FETCH_EDUCATION_LEVELS_FAIL';

export const DISPATCH_SERVICE_MESSAGE = 'DISPATCH_SERVICE_MESSAGE';

export const UPDATE_BREADCRUMBS = 'UPDATE_BREADCRUMBS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const UPDATE_PROFILE_FORM_ERRORS = 'UPDATE_PROFILE_FORM_ERRORS';
