export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';

export const FETCH_SEARCH_AUTOSUGGEST_OPTIONS = 'FETCH_SEARCH_AUTOSUGGEST_OPTIONS';
export const FETCH_SEARCH_AUTOSUGGEST_OPTIONS_SUCCESS = 'FETCH_SEARCH_AUTOSUGGEST_OPTIONS_SUCCESS';
export const FETCH_SEARCH_AUTOSUGGEST_OPTIONS_FAIL = 'FETCH_SEARCH_AUTOSUGGEST_OPTIONS_FAIL';
