export const FETCH_EMPLOYER = 'FETCH_EMPLOYER';
export const FETCH_EMPLOYER_SUCCESS = 'FETCH_EMPLOYER_SUCCESS';
export const FETCH_EMPLOYER_FAIL = 'FETCH_EMPLOYER_FAIL';

export const UPDATE_COMPANY_INFO = 'UPDATE_COMPANY_INFO';
export const UPDATE_COMPANY_INFO_SUCCESS = 'UPDATE_COMPANY_INFO_SUCCESS';
export const UPDATE_COMPANY_INFO_FAIL = 'UPDATE_COMPANY_INFO_FAIL';

export const UPDATE_COMPANY_LOGO = 'UPDATE_COMPANY_LOGO';
export const UPDATE_COMPANY_LOGO_SUCCESS = 'UPDATE_COMPANY_LOGO_SUCCESS';
export const UPDATE_COMPANY_LOGO_FAIL = 'UPDATE_COMPANY_LOGO_FAIL';

export const UPDATE_COMPANY_HEADOFFICE = 'UPDATE_COMPANY_HEADOFFICE';
export const UPDATE_COMPANY_HEADOFFICE_SUCCESS = 'UPDATE_COMPANY_HEADOFFICE_SUCCESS';
export const UPDATE_COMPANY_HEADOFFICE_FAIL = 'UPDATE_COMPANY_HEADOFFICE_FAIL';

export const UPDATE_COMPANY_BRANCHES = 'UPDATE_COMPANY_BRANCHES';
export const UPDATE_COMPANY_BRANCHES_SUCCESS = 'UPDATE_COMPANY_BRANCHES_SUCCESS';
export const UPDATE_COMPANY_BRANCHES_FAIL = 'UPDATE_COMPANY_BRANCHES_FAIL';

export const UPDATE_COMPANY_FORM_ERRORS = 'UPDATE_COMPANY_FORM_ERRORS';
