export const FETCH_MY_CVS = 'FETCH_MY_CVS';
export const FETCH_MY_CVS_SUCCESS = 'FETCH_MY_CVS_SUCCESS';
export const FETCH_MY_FAIL = 'FETCH_MY_FAIL';

export const FETCH_CVS = 'FETCH_CVS';
export const FETCH_CVS_SUCCESS = 'FETCH_CVS_SUCCESS';
export const FETCH_CVS_FAIL = 'FETCH_CVS_FAIL';

export const FETCH_MORE_CVS = 'FETCH_MORE_CVS';
export const FETCH_MORE_CVS_SUCCESS = 'FETCH_MORE_CVS_SUCCESS';
export const FETCH_MORE_CVS_FAIL = 'FETCH_MORE_CVS_FAIL';

export const FETCH_CV = 'FETCH_CV';
export const FETCH_CV_SUCCESS = 'FETCH_CV_SUCCESS';
export const FETCH_CV_FAIL = 'FETCH_CV_FAIL';

export const UPDATE_CV_PHOTO = 'UPDATE_CV_PHOTO';
export const UPDATE_CV_PHOTO_SUCCESS = 'UPDATE_CV_PHOTO_SUCCESS';
export const UPDATE_CV_PHOTO_FAIL = 'UPDATE_CV_PHOTO_FAIL';

export const UPDATE_CV_TITLEBOX = 'UPDATE_CV_TITLEBOX';
export const UPDATE_CV_TITLEBOX_SUCCESS = 'UPDATE_CV_TITLEBOX_SUCCESS';
export const UPDATE_CV_TITLEBOX_FAIL = 'UPDATE_CV_TITLEBOX_FAIL';

export const UPDATE_CV_ACTIVITY = 'UPDATE_CV_ACTIVITY';
export const UPDATE_CV_ACTIVITY_SUCCESS = 'UPDATE_CV_ACTIVITY_SUCCESS';
export const UPDATE_CV_ACTIVITY_FAIL = 'UPDATE_CV_ACTIVITY_FAIL';

export const FETCH_POSITIONS = 'FETCH_POSITIONS';
export const FETCH_POSITIONS_SUCCESS = 'FETCH_POSITIONS_SUCCESS';

export const FETCH_EXPERIENCE_SPECIALTY = 'FETCH_EXPERIENCE_SPECIALTY';
export const FETCH_EXPERIENCE_SPECIALTY_SUCCESS = 'FETCH_EXPERIENCE_SPECIALTY_SUCCESS';

export const FETCH_SKILLS = 'FETCH_SKILLS';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';

export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';

export const FETCH_EMPLOYMENT_TYPES = 'FETCH_EMPLOYMENTS';
export const FETCH_EMPLOYMENT_TYPES_SUCCESS = 'FETCH_EMPLOYMENTS_TYPES_SUCCESS';

export const UPDATE_SUMMARYBOX = 'UPDATE_SUMMARYBOX';
export const UPDATE_SUMMARYBOX_SUCCESS = 'UPDATE_SUMMARYBOX_SUCCESS';
export const UPDATE_SUMMARYBOX_FAIL = 'UPDATE_SUMMARYBOX_FAIL';

export const UPDATE_CV_LANGUAGES = 'UPDATE_CV_LANGUAGES';
export const UPDATE_CV_LANGUAGES_SUCCESS = 'UPDATE_CV_LANGUAGES_SUCCESS';
export const UPDATE_CV_LANGUAGES_FAIL = 'UPDATE_CV_LANGUAGES_FAIL';

export const UPDATE_CV_EXPERIENCE = 'UPDATE_CV_EXPERIENCE';
export const UPDATE_CV_EXPERIENCE_SUCCESS = 'UPDATE_CV_EXPERIENCE_SUCCESS';
export const UPDATE_CV_EXPERIENCE_FAIL = 'UPDATE_CV_EXPERIENCE_FAIL';

export const UPDATE_CV_EDUCATION = 'UPDATE_CV_EDUCATION';
export const UPDATE_CV_EDUCATION_SUCCESS = 'UPDATE_CV_EDUCATION_SUCCESS';
export const UPDATE_CV_EDUCATION_FAIL = 'UPDATE_CV_EDUCATION_FAIL';

export const UPDATE_CV_COURSES = 'UPDATE_CV_COURSES';
export const UPDATE_CV_COURSES_SUCCESS = 'UPDATE_CV_COURSES_SUCCESS';
export const UPDATE_CV_COURSES_FAIL = 'UPDATE_CV_COURSES_FAIL';

export const CREATE_CV = 'CREATE_CV';
export const CREATE_CV_SUCCESS = 'CREATE_CV_SUCCESS';
export const CREATE_CV_FAIL = 'CREATE_CV_FAIL';

export const DELETE_CV = 'DELETE_CV';
export const DELETE_CV_SUCCESS = 'DELETE_CV_SUCCESS';
export const DELETE_CV_FAIL = 'DELETE_CV_FAIL';

export const COPY_CV = 'COPY_CV';
export const COPY_CV_SUCCESS = 'COPY_CV_SUCCESS';
export const COPY_CV_FAIL = 'COPY_CV_FAIL';

export const ADD_CV_TO_FAVORITES = 'ADD_CV_TO_FAVORITES';
export const ADD_CV_TO_FAVORITES_SUCCESS = 'ADD_CV_TO_FAVORITES_SUCCESS';
export const ADD_CV_TO_FAVORITES_FAIL = 'ADD_CV_TO_FAVORITES_FAIL';

export const REMOVE_CV_FROM_FAVORITES = 'REMOVE_CV_FROM_FAVORITES';
export const REMOVE_CV_FROM_FAVORITES_SUCCESS = 'REMOVE_CV_FROM_FAVORITES_SUCCESS';
export const REMOVE_CV_FROM_FAVORITES_FAIL = 'REMOVE_CV_FROM_FAVORITES_FAIL';

export const ADD_CV_LIST_TO_FAVORITES = 'ADD_CV_LIST_TO_FAVORITES';
export const ADD_CV_LIST_TO_FAVORITES_SUCCESS = 'ADD_CV_LIST_TO_FAVORITES_SUCCESS';
export const ADD_CV_LIST_TO_FAVORITES_FAIL = 'ADD_CV_LIST_TO_FAVORITES_FAIL';

export const REMOVE_CV_LIST_FROM_FAVORITES = 'REMOVE_CV_LIST_FROM_FAVORITES';
export const REMOVE_CV_LIST_FROM_FAVORITES_SUCCESS = 'REMOVE_CV_LIST_FROM_FAVORITES_SUCCESS';
export const REMOVE_CV_LIST_FROM_FAVORITES_FAIL = 'REMOVE_CV_LIST_FROM_FAVORITES_FAIL';

export const UNSELECT_ALL_CVS = 'UNSELECT_ALL_CVS';
export const TOGGLE_CV_SELECTION = 'TOGGLE_CV_SELECTION';

export const UPDATE_CV_FORM_ERRORS = 'UPDATE_CV_FORM_ERRORS';

export const FETCH_FAVORITES_CVS = 'FETCH_FAVORITES_CVS';
export const FETCH_FAVORITES_CVS_SUCCESS = 'FETCH_FAVORITES_CVS_SUCCESS';
export const FETCH_FAVORITES_CVS_FAIL = 'FETCH_FAVORITES_CVS_FAIL';

export const FETCH_FILTER_FAVORITES_CVS = 'FETCH_FILTER_FAVORITES_CVS';
export const FETCH_FILTER_FAVORITES_CVS_SUCCESS = 'FETCH_FILTER_FAVORITES_CVS_SUCCESS';
export const FETCH_FILTER_FAVORITES_CVS_FAIL = 'FETCH_FILTER_FAVORITES_CVS_FAIL';

export const FETCH_MATCHING_CVS = 'FETCH_MATCHING_CVS';
export const FETCH_MATCHING_CVS_SUCCESS = 'FETCH_MATCHING_CVS_SUCCESS';
export const FETCH_MATCHING_CVS_FAIL = 'FETCH_MATCHING_CVS_FAIL';
